### ISSUE TITLE
Make `use_continuation: true` and `assertion: :bot`the default

### ISSUE THREAD

**Issue by xbony2** [FTB-Gamepedia/MediaWiki-Butt-Ruby#62] opened 2017-07-13 15:38 UTC

**Comment by elifoster** [comment] 2017-10-17 18:50
Duplicate of #66

**Closed by elifoster** 2017-10-17 18:50 UTC
Labels: breaking change, duplicate, enhancement, prio:med

**Comment by xbony2** [comment] 2017-10-17 21:55
mine was first you frickin' gobber D:

**Comment by elifoster** [comment] 2017-10-17 22:00
Yeah but mine was more detailed :joy:

**Comment by xbony2** [comment] 2017-10-17 22:15
no
